/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestoresRouteImport } from './routes/gestores'
import { Route as FerramentaRouteImport } from './routes/ferramenta'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as ContadoresRouteImport } from './routes/contadores'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CotacaoTokenRouteImport } from './routes/cotacao.$token'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as AdminPrestacaoRouteImport } from './routes/admin.prestacao'
import { Route as AdminPainelRouteImport } from './routes/admin.painel'
import { Route as AdminOrcamentosRouteImport } from './routes/admin.orcamentos'
import { Route as AdminObjetosRouteImport } from './routes/admin.objetos'
import { Route as AdminModelosRouteImport } from './routes/admin.modelos'
import { Route as AdminFornecedoresRouteImport } from './routes/admin.fornecedores'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCapturaRouteImport } from './routes/admin.captura'
import { Route as AdminAprovacoesRouteImport } from './routes/admin.aprovacoes'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminCotacoesIdRouteImport } from './routes/admin.cotacoes.$id'
import { Route as ApiPublicCotacaoTokenRouteImport } from './routes/api/public/cotacao.$token'
import { Route as ApiPublicCotacaoTokenPdfRouteImport } from './routes/api/public/cotacao.$token.pdf'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoresRoute = GestoresRouteImport.update({
  id: '/gestores',
  path: '/gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentaRoute = FerramentaRouteImport.update({
  id: '/ferramenta',
  path: '/ferramenta',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContadoresRoute = ContadoresRouteImport.update({
  id: '/contadores',
  path: '/contadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CotacaoTokenRoute = CotacaoTokenRouteImport.update({
  id: '/cotacao/$token',
  path: '/cotacao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrestacaoRoute = AdminPrestacaoRouteImport.update({
  id: '/prestacao',
  path: '/prestacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPainelRoute = AdminPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosRoute = AdminOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObjetosRoute = AdminObjetosRouteImport.update({
  id: '/objetos',
  path: '/objetos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelosRoute = AdminModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFornecedoresRoute = AdminFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapturaRoute = AdminCapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAprovacoesRoute = AdminAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCotacoesIdRoute = AdminCotacoesIdRouteImport.update({
  id: '/cotacoes/$id',
  path: '/cotacoes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCotacaoTokenRoute = ApiPublicCotacaoTokenRouteImport.update({
  id: '/api/public/cotacao/$token',
  path: '/api/public/cotacao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCotacaoTokenPdfRoute =
  ApiPublicCotacaoTokenPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => ApiPublicCotacaoTokenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contadores': typeof ContadoresRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/ferramenta': typeof FerramentaRoute
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/captura': typeof AdminCapturaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/objetos': typeof AdminObjetosRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/prestacao': typeof AdminPrestacaoRoute
  '/api/extract': typeof ApiExtractRoute
  '/cotacao/$token': typeof CotacaoTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cotacoes/$id': typeof AdminCotacoesIdRoute
  '/api/public/cotacao/$token': typeof ApiPublicCotacaoTokenRouteWithChildren
  '/api/public/cotacao/$token/pdf': typeof ApiPublicCotacaoTokenPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contadores': typeof ContadoresRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/ferramenta': typeof FerramentaRoute
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/captura': typeof AdminCapturaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/objetos': typeof AdminObjetosRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/prestacao': typeof AdminPrestacaoRoute
  '/api/extract': typeof ApiExtractRoute
  '/cotacao/$token': typeof CotacaoTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cotacoes/$id': typeof AdminCotacoesIdRoute
  '/api/public/cotacao/$token': typeof ApiPublicCotacaoTokenRouteWithChildren
  '/api/public/cotacao/$token/pdf': typeof ApiPublicCotacaoTokenPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contadores': typeof ContadoresRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/ferramenta': typeof FerramentaRoute
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/captura': typeof AdminCapturaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/objetos': typeof AdminObjetosRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/prestacao': typeof AdminPrestacaoRoute
  '/api/extract': typeof ApiExtractRoute
  '/cotacao/$token': typeof CotacaoTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cotacoes/$id': typeof AdminCotacoesIdRoute
  '/api/public/cotacao/$token': typeof ApiPublicCotacaoTokenRouteWithChildren
  '/api/public/cotacao/$token/pdf': typeof ApiPublicCotacaoTokenPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contadores'
    | '/demonstracao'
    | '/ferramenta'
    | '/gestores'
    | '/login'
    | '/obrigado'
    | '/orcamentos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/aprovacoes'
    | '/admin/captura'
    | '/admin/configuracoes'
    | '/admin/fornecedores'
    | '/admin/modelos'
    | '/admin/objetos'
    | '/admin/orcamentos'
    | '/admin/painel'
    | '/admin/prestacao'
    | '/api/extract'
    | '/cotacao/$token'
    | '/admin/'
    | '/admin/cotacoes/$id'
    | '/api/public/cotacao/$token'
    | '/api/public/cotacao/$token/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contadores'
    | '/demonstracao'
    | '/ferramenta'
    | '/gestores'
    | '/login'
    | '/obrigado'
    | '/orcamentos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/aprovacoes'
    | '/admin/captura'
    | '/admin/configuracoes'
    | '/admin/fornecedores'
    | '/admin/modelos'
    | '/admin/objetos'
    | '/admin/orcamentos'
    | '/admin/painel'
    | '/admin/prestacao'
    | '/api/extract'
    | '/cotacao/$token'
    | '/admin'
    | '/admin/cotacoes/$id'
    | '/api/public/cotacao/$token'
    | '/api/public/cotacao/$token/pdf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contadores'
    | '/demonstracao'
    | '/ferramenta'
    | '/gestores'
    | '/login'
    | '/obrigado'
    | '/orcamentos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/aprovacoes'
    | '/admin/captura'
    | '/admin/configuracoes'
    | '/admin/fornecedores'
    | '/admin/modelos'
    | '/admin/objetos'
    | '/admin/orcamentos'
    | '/admin/painel'
    | '/admin/prestacao'
    | '/api/extract'
    | '/cotacao/$token'
    | '/admin/'
    | '/admin/cotacoes/$id'
    | '/api/public/cotacao/$token'
    | '/api/public/cotacao/$token/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContadoresRoute: typeof ContadoresRoute
  DemonstracaoRoute: typeof DemonstracaoRoute
  FerramentaRoute: typeof FerramentaRoute
  GestoresRoute: typeof GestoresRoute
  LoginRoute: typeof LoginRoute
  ObrigadoRoute: typeof ObrigadoRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiExtractRoute: typeof ApiExtractRoute
  CotacaoTokenRoute: typeof CotacaoTokenRoute
  ApiPublicCotacaoTokenRoute: typeof ApiPublicCotacaoTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestores': {
      id: '/gestores'
      path: '/gestores'
      fullPath: '/gestores'
      preLoaderRoute: typeof GestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta': {
      id: '/ferramenta'
      path: '/ferramenta'
      fullPath: '/ferramenta'
      preLoaderRoute: typeof FerramentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contadores': {
      id: '/contadores'
      path: '/contadores'
      fullPath: '/contadores'
      preLoaderRoute: typeof ContadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cotacao/$token': {
      id: '/cotacao/$token'
      path: '/cotacao/$token'
      fullPath: '/cotacao/$token'
      preLoaderRoute: typeof CotacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prestacao': {
      id: '/admin/prestacao'
      path: '/prestacao'
      fullPath: '/admin/prestacao'
      preLoaderRoute: typeof AdminPrestacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/painel': {
      id: '/admin/painel'
      path: '/painel'
      fullPath: '/admin/painel'
      preLoaderRoute: typeof AdminPainelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos': {
      id: '/admin/orcamentos'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AdminOrcamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/objetos': {
      id: '/admin/objetos'
      path: '/objetos'
      fullPath: '/admin/objetos'
      preLoaderRoute: typeof AdminObjetosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modelos': {
      id: '/admin/modelos'
      path: '/modelos'
      fullPath: '/admin/modelos'
      preLoaderRoute: typeof AdminModelosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fornecedores': {
      id: '/admin/fornecedores'
      path: '/fornecedores'
      fullPath: '/admin/fornecedores'
      preLoaderRoute: typeof AdminFornecedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/captura': {
      id: '/admin/captura'
      path: '/captura'
      fullPath: '/admin/captura'
      preLoaderRoute: typeof AdminCapturaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aprovacoes': {
      id: '/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AdminAprovacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cotacoes/$id': {
      id: '/admin/cotacoes/$id'
      path: '/cotacoes/$id'
      fullPath: '/admin/cotacoes/$id'
      preLoaderRoute: typeof AdminCotacoesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cotacao/$token': {
      id: '/api/public/cotacao/$token'
      path: '/api/public/cotacao/$token'
      fullPath: '/api/public/cotacao/$token'
      preLoaderRoute: typeof ApiPublicCotacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cotacao/$token/pdf': {
      id: '/api/public/cotacao/$token/pdf'
      path: '/pdf'
      fullPath: '/api/public/cotacao/$token/pdf'
      preLoaderRoute: typeof ApiPublicCotacaoTokenPdfRouteImport
      parentRoute: typeof ApiPublicCotacaoTokenRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAprovacoesRoute: typeof AdminAprovacoesRoute
  AdminCapturaRoute: typeof AdminCapturaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFornecedoresRoute: typeof AdminFornecedoresRoute
  AdminModelosRoute: typeof AdminModelosRoute
  AdminObjetosRoute: typeof AdminObjetosRoute
  AdminOrcamentosRoute: typeof AdminOrcamentosRoute
  AdminPainelRoute: typeof AdminPainelRoute
  AdminPrestacaoRoute: typeof AdminPrestacaoRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCotacoesIdRoute: typeof AdminCotacoesIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAprovacoesRoute: AdminAprovacoesRoute,
  AdminCapturaRoute: AdminCapturaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFornecedoresRoute: AdminFornecedoresRoute,
  AdminModelosRoute: AdminModelosRoute,
  AdminObjetosRoute: AdminObjetosRoute,
  AdminOrcamentosRoute: AdminOrcamentosRoute,
  AdminPainelRoute: AdminPainelRoute,
  AdminPrestacaoRoute: AdminPrestacaoRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCotacoesIdRoute: AdminCotacoesIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPublicCotacaoTokenRouteChildren {
  ApiPublicCotacaoTokenPdfRoute: typeof ApiPublicCotacaoTokenPdfRoute
}

const ApiPublicCotacaoTokenRouteChildren: ApiPublicCotacaoTokenRouteChildren = {
  ApiPublicCotacaoTokenPdfRoute: ApiPublicCotacaoTokenPdfRoute,
}

const ApiPublicCotacaoTokenRouteWithChildren =
  ApiPublicCotacaoTokenRoute._addFileChildren(
    ApiPublicCotacaoTokenRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContadoresRoute: ContadoresRoute,
  DemonstracaoRoute: DemonstracaoRoute,
  FerramentaRoute: FerramentaRoute,
  GestoresRoute: GestoresRoute,
  LoginRoute: LoginRoute,
  ObrigadoRoute: ObrigadoRoute,
  OrcamentosRoute: OrcamentosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiExtractRoute: ApiExtractRoute,
  CotacaoTokenRoute: CotacaoTokenRoute,
  ApiPublicCotacaoTokenRoute: ApiPublicCotacaoTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
